import os, inspect
Import ("env")
Import ("include_mp")
Import ("include_mpi")
Import ("objects")

def directory (path, dirname):
    if dirname [len (path) + 1:] == "":
        return ""
    else:
        return dirname [len (path) + 1:] + "/"

path = os.path.dirname (inspect.getfile (inspect.currentframe ()))

for dirname, dirnames, filenames in os.walk (path):
    if dirname != path:
        for filename in filenames:
            # if "mpi-3-block-solver-test.hpp" not in filename:
                # continue
            if filename == "SConscript":
                env.SConscript(dirname + '/' + filename, variant_dir = os.path.join (".", directory (path, dirname)), duplicate = 0, exports = {'env': env, "objects": objects, "include_cuda" : include_cuda, "include_mp": include_mp})
            if filename.split ('.') [-1] == 'hpp':
                if filename [:3] == "mpi":
                    if include_mpi:
                        env.CxxTest('tests_' + filename, source = [os.path.relpath (dirname, path) + '/' + filename] + objects, ranks = [int (filename [4])]) 
                else:
                    env.CxxTest('tests_' + filename, source = [os.path.relpath (dirname, path) + '/' + filename] + objects)
