language: c++
compiler: gcc
before_install:
    - sudo apt-get install libfftw3-dev libfftw3-doc
    - sudo apt-get install libboost-all-dev
    - wget https://github.com/jbeder/yaml-cpp/archive/master.zip
    - unzip master.zip -d yaml-cpp
    - mkdir yaml-cpp/build
    - cd yaml-cpp/build
    - cmake ..
    - make
    - sudo make install
    - cd ../..
    - sudo apt-get install log4cplus
    - sudo apt-get install netcdf_c++4
    - sudo apt-get install gsl
    - sudo apt-get install lapack
script: scons
