language: c++
compiler: gcc
before_install:
    - sudo apt-get install libfftw3-dev libfftw3-doc
    - sudo apt-get install libboost-all-dev
    - wget https://github.com/jbeder/yaml-cpp/archive/master.zip
    - unzip master.zip -d yaml-cpp
    - mkdir yaml-cpp/yaml-cpp-master/build
    - cd yaml-cpp/yaml-cpp-master/build
    - cmake ..
    - make
    - sudo make install
    - cd ../../..
    - sudo apt-get install libnetcdf-dev
    - sudo apt-get install libgsl0ldbl
    - sudo apt-get install liblapack-dev
script: scons
