language: c++
compiler: gcc

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: required

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - libfftw3-dev
            - libboost-all-dev
            - libgsl0-dev
            - liblapack-dev
            - libnetcdf-dev
            - cmake
        sources:
            - kubuntu-ppa/backports

before_install:
    - wget https://github.com/jbeder/yaml-cpp/archive/master.zip
    - unzip master.zip -d yaml-cpp
    - mkdir yaml-cpp/yaml-cpp-master/build
    - cd yaml-cpp/yaml-cpp-master/build
    - cmake ..
    - make
    - sudo make install
    - cd ../../..
    - rm master.zip
    - wget https://github.com/Unidata/netcdf-cxx4/archive/master.zip
    - unzip master.zip -d netcdf-cxx4
    - ls netcdf-cxx4
    - mkdir netcdf-cxx4/netcdf-cxx4-master/build
    - cd netcdf-cxx4/netcdf-cxx4-master/build
    - cmake ..
    - make
    - sudo make install

script: scons
