language: c++
compiler: gcc

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: required

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - libfftw3-dev
            - libboost-all-dev
            - libgsl0-dev
            - liblapack-dev
            - libnetcdf-dev
            - cmake
        sources:
            - kubuntu-backports

before_install:
    - wget https://github.com/jbeder/yaml-cpp/archive/master.zip
    - unzip master.zip
    - mkdir yaml-cpp-master/build
    - cd yaml-cpp-master/build
    - cmake ..
    - make
    - sudo make install
    - cd ../..
    - wget https://github.com/Unidata/netcdf-cxx4/archive/v4.2.1.zip
    - unzip v4.2.1.zip
    - mkdir netcdf-cxx4-4.2.1/build
    - cd netcdf-cxx4-4.2.1/build
    - cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr
    - make
    - sudo make install
    - cd ../..

script: scons
