language: c++
compiler: gcc

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: required

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - libfftw3-dev
            - libboost-all-dev
            - libgsl0-dev
            - liblapack-dev
            - libnetcdf-dev

before_install:
    - git clone git@github.com:Unidata/netcdf-cxx4.git
    - wget https://github.com/jbeder/yaml-cpp/archive/master.zip
    - unzip master.zip -d yaml-cpp
    - mkdir yaml-cpp/yaml-cpp-master/build
    - cd yaml-cpp/yaml-cpp-master/build
    - cmake ..
    - make
    - sudo make install
    - cd ../../..

script: scons
