Import ("env")
Import ("objects")

for lib in ["lapack", "blas", "atlas", "fftw3"]:
    if lib not in env ['LIBS']:
        env.Append (LIBS = lib)

objects.append (env.Object ("element.cpp"))

objects.append (env.Object ("diffusion.cpp"))

objects.append (env.Object ("advection.cpp"))

objects.append (env.Object ("solver.cpp"))
