Import ("env")
Import ("objects")
Import ("cuda_objects")

for lib in ["fftw3"]:
    if lib not in env ['LIBS']:
        env.Append (LIBS = lib)

objects.append (env.Object ("element_one_d.cpp"))

objects.append (env.Object ("diffusion_one_d.cpp"))

objects.append (env.Object ("advection_one_d.cpp"))

objects.append (env.Object ("solver_one_d.cpp"))

for lib in ["cufft"]:
    if lib not in env ['LIBS']:
        env.Append (LIBS = lib)

objects.append (env.Object ("fftw_one_d_cuda.cu"))
