Import ("env")
Import ("objects")
Import ("cuda_objects")
Import ("include_mp")

conf = Configure (env)

conf.CheckLib ("fftw3")
conf.CheckLib ("fftw3f")
        
conf.CheckLib ("fftw3_omp")
conf.CheckLib ("fftw3f_omp")
conf.CheckLib ("m")
    
env = conf.Finish ()

objects.append (env.Object ("element_two_d.cpp"))

objects.append (env.Object ("plan_two_d.cpp"))

objects.append (env.Object ("transform_two_d.cpp"))

objects.append (env.Object ("solver_two_d.cpp"))

