Import ("env")
Import ("cuda_objects")
Import ("include_cuda")

if include_cuda:
    cuda_objects.append (env.Object ("utils_cublas.cu"))
    cuda_objects.append (env.Object ("solver_utils_cuda.cu"))
