Import ("env")
Import ("cuda_objects")

cuda_objects.append (env.Object ("dgetrs.cu"))
cuda_objects.append (env.Object ("dlaswp.cu"))
cuda_objects.append (env.Object ("dtrsm.cu"))
cuda_objects.append (env.Object ("lsame.cu"))
cuda_objects.append (env.Object ("xerbla.cu"))

env.Default (env.Program(target = "../../../run/test", source = (["test.cu"] + cuda_objects)))

cuda_objects.append (env.Object ("utils_cublas.cu"))


