init:
    scale: 100.0
    mean: 0.0
    sigma: 10.
grid:
    nrhs: 4096
    nb: 1
    x:
        points: 32
        width: 100.0
    z:
        points: 32
        width: 100.0
    rezone:
        check_every: 500
        min_size: 20.0
        max_size: 50.0
        n_tries: 1
        iters_fixed_t: 1
        step_size: 5.0
        k: 1.0
        t_initial: 8e-1
        mu_t: 1.003
        t_min: 2e-1
time:
    steps: 1000
    init: 1.0e-5
    max: 1.e-0
    mult: 1.1
    safety: 0.08
    cfl: 0.1
    alpha: 1.0
    allow: 1000.0
temperature:
    diffusion: 1.0
    advection: 1.0
    stratification: -1.0
composition:
    diffusion: 0.1
    advection: 1.0
    stratification: -2.0
velocity:
    diffusion: 0.1
    advection: 1.0
    buoyancy:
        temperature: 0.1
        composition: -0.1
input:
    file: input_%02i
    full: true
output:
    file: sc_gwave_%02i
    transform_file: sc_gwave_t_%02i
    every: 10
    stat:
        file: sc_gwave_%02i
        every: 50
    merge_file: merge_%04i
    full: false
parallel:
    maxthreads: 4
    transform:
        threads: 1
        subthreads: 1
