Import ("env")
Import ("cuda_objects")
Import ("include_cuda")

if include_cuda:
    for lib in ["cufft"]:
        if lib not in env ['LIBS']:
            env.Append (LIBS = lib)
            
    # cuda_objects.append (env.Object ("element_one_d_cuda.cpp"))
    cuda_objects.append (env.Object ("transform_one_d_cuda.cu"))
    # cuda_objects.append (env.Object ("solver_one_d_cuda.cu"))
    # cuda_objects.append (env.Object ("diffusion_one_d_cuda.cpp"))
