Import ("env")
Import ("cuda_objects")

cuda_objects.append (env.Object ("element_one_d_cuda.cpp"))

for lib in ["cufft"]:
    if lib not in env ['LIBS']:
        env.Append (LIBS = lib)

cuda_objects.append (env.Object ("fftw_one_d_cuda.cu"))

cuda_objects.append (env.Object ("solver_one_d_cuda.cu"))
