Import ("env")
Import ("objects")

objects.append (env.Object ("element_one_d_cuda.cpp"))

for lib in ["cufft"]:
    if lib not in env ['LIBS']:
        env.Append (LIBS = lib)

objects.append (env.Object ("fftw_one_d_cuda.cu"))
