Import ("env")
Import ("objects")
Import ("cuda_objects")
Import ("include_cuda")
Import ("include_mp")

conf = Configure (env)

if include_cuda:
    conf.CheckLib ("cublas")

for lib in ["lapack", "blas", "atlas", "netcdf_c++", "netcdf"]:
    conf.CheckLib (lib)

env = conf.Finish ()

if not include_mp:
    objects.append (env.Object ("utils.cpp"))
    objects.append (env.Object ("solver_utils.cpp"))

objects.append (env.Object ("interpolate.cpp"))

objects.append (env.Object ("block_solver.cpp"))

objects.append (env.Object ("io.cpp"))
