Import ("env")
Import ("objects")
Import ("include_cuda")
Import ("include_mp")

conf = Configure (env)

if include_cuda:
    conf.CheckLib ("cublas")

if not conf.CheckLib ("ptlapack"):
    conf.CheckLib ("lapack")
if not conf.CheckLib ("ptf77blas"):
    conf.CheckLib ("blas")
if not conf.CheckLib ("ptcblas"):
    conf.CheckLib ("cblas")

for lib in ["atlas", "netcdf_c++", "netcdf", "irc", "imf", "yaml-cpp"]:
    conf.CheckLib (lib)

env = conf.Finish ()

objects.append (env.Object ("utils.cpp"))
objects.append (env.Object ("solver_utils.cpp"))

objects.append (env.Object ("interpolate.cpp"))

objects.append (env.Object ("block_solver.cpp"))

objects.append (env.Object ("io.cpp"))
