Import ("env")
Import ("include_cuda")

conf = Configure (env)

if include_cuda:
    conf.CheckLib ("cublas")

conf.CheckLib ("lapack")
conf.CheckLib ("cblas")
conf.CheckLib ("f77blas")

conf.CheckLib ("atlas")

env = conf.Finish ()
