Import ("*")

import os, inspect

conf = Configure (env)

for lib in ["irc", "imf", "yaml-cpp"]:
    conf.CheckLib (lib)

conf.CheckLib ("netcdf_c++4")
conf.CheckLib ("netcdf")
conf.CheckLib ("hdf5")
conf.CheckLib ("hdf5_hl")

env = conf.Finish ()
