import os, inspect
Import ("env")

conf = Configure (env)

objects = []
if conf.CheckLib ("log4cxx"):
    env.Append (CPPFLAGS = ["-D_LOG4CXX"])

env = conf.Finish ()

path = os.path.dirname (inspect.getfile (inspect.currentframe ()))

for dirname, dirnames, filenames in os.walk (path):
    for subdirname in dirnames:
        env.SConscript('%s/SConscript' % os.path.join (path, subdirname), variant_dir = os.path.join (".", subdirname), duplicate = 0, exports = {'env': env, "objects": objects})

objects.append (env.Object ("config.cpp"))

objects.append (env.Object ("test.cu"))

env.Default (env.Program(target = "../run/main", source = (["main.cpp"] + objects)))

env.Default (env.Program(target = "../run/main_cuda", source = (["main_cuda.cpp"] + objects)))
