init:
    scale: 0.01
grid:
    x:
        points: 128
        width: 100.0
    z:
        points: 128
        width: 100.0
time:
    steps: 6000
    init: 1e-7
    max: 1e-2
    mult: 1.1
equations:
    temperature:
        diffusion: 1.0
        advection: 1.0
        sources:
            z_velocity: 1.0
    composition:
        diffusion: 0.1
        advection: 1.0
        sources:
            z_velocity: 1.1
    velocity:
        diffusion: 6.8
        advection: 1.0
    z_velocity:
        sources:
            temperature: 6.8
            composition: -6.8
    pressure:
        ignore: false
output:
    every: 20
    stat:
        every: 10
parallel:
    maxthreads: 8
